### ISSUE TITLE
After several experiments, the same computer on the test index is different.

### ISSUE THREAD

**Issue by HenanNormalUnversity** [AngeLouCN/CaraNet#21]
Hello, I am very sorry to have occupied your study time. I have a question to ask you! The graphics card of my desktop computer is 3090, I downloaded the source code on your homepage (Github), and conducted several experiments, adding the indexes of mDice and mIOU. After testing and comparing the results of many experiments, I found that for the test dataset Kvasir, the difference of mDice indexes was as high as 1.27 percent. For the other four test sets, the gap may be larger, which is not normal. Why is this? Sorry to trouble you. Sorry again for taking up your time!

**Comment by AngeLouCN** [comment]
Hi, Thank you for your interests. I guess you use the higher version PyTorch. You can try to add the **align_corners = 'True'** in **Caranet.py** where used the **F.interpolate** functions. It is caused by the PyTorch version change. Also, if you directly use some python library to calculate the mDice or mIOU, it could be difference. That's why I used the matlab code provided by PraNet.
